### ISSUE TITLE
Longer Password list

### ISSUE THREAD

**Issue by pachonk** [HCLarsen/devise-uncommon_password#1] opened 2017-07-22 22:41 UTC
If you find that 100 passwords is not enough, here's my go-to password list:
https://github.com/danielmiessler/SecLists/tree/master/Passwords

**Comment by HCLarsen** [comment] 2017-07-22 23:18
Thank you. Greatly appreciated. In future versions of this gem, I do plan to add functionality that allows the developer to tweak the number of passwords checked against.

**Comment by bradseefeld** [comment] 2017-09-06 20:53
This is also a blocker for us. We would like to use 100k or 1M common passwords for our check. Being able to config the extension to point to a custom list would be great.

**Comment by HCLarsen** [comment] 2017-09-07 05:43
Finding a list that long of passwords that already meets Devise's 8 character minimum isn't easy. Most of those "common passwords" are 4-6 characters long.

**Comment by HCLarsen** [comment] 2017-09-07 19:25
I fail to understand what you're getting at. If an organization cares enough about security to add extensions for the Devise Gem, why would they go into devise.rb to change the minimum password length?

Larger lists, along with customization for the length of list, will be added to future versions. That is already in the road map. Give me another couple of weeks, and I should have that update loaded.

**Comment by bradseefeld** [comment] 2017-09-07 20:23
I didnt mean they would be shortening it necessarily. They could be increasing the min length to 12, for example, in which case even more from the existing list would now be 'invalid'. 

Having the path customizable in a future version would be great!

**Comment by pachonk** [comment] 2017-09-07 20:29
You could run a map enum based on devise's min password setting.
Another option is just using Troy Hunt's list.

**Comment by HCLarsen** [comment] 2017-09-08 19:00
@pachonk Is Troy Hunt's list better than the ones you linked to before?

**Comment by HCLarsen** [comment] 2017-09-08 19:01
@bradseefeld if they're increasing the min length instead of decreasing, then your argument of having a list that includes 4 character passwords doesn't make sense to me.

**Comment by pachonk** [comment] 2017-09-08 19:06
Troy Hunt's list is definitely more complete, but it's 5+GB and it's sha1 hashes which would require some re coding from what you currently have.

**Comment by HCLarsen** [comment] 2017-09-08 19:08
Hmm, yes. That would require some big changes. I'll keep that in mind for the future, but for now, the next version will just have one of the larger lists that you provided up above. 10M is still a large set of passwords to choose from.

**Comment by pachonk** [comment] 2017-09-08 19:15
I think running some sort of select or reject on the list based on devise max password could make sense too.
You could use ag - the silver searcher which is super fast and not allow partial passwords too

**Comment by HCLarsen** [comment] 2017-09-08 19:19
That's my thoughts exactly. Using select on the array with between? using the range that Devise provides. That way, if the developer changes the range, the list provided will be relevant.

**Comment by pachonk** [comment] 2017-09-08 19:21
I wouldn't care about the max much... Most people don't touch it and it'll just waste time on a comparison that is rarely going to return "false" on the max side.

**Comment by pachonk** [comment] 2017-09-08 19:25
I didn't look at source code.much... but thats a lot of passwords to have in an array. Consider using RDS in some way at that scale.

**Comment by HCLarsen** [comment] 2017-09-08 19:28
I'm not familiar with RDS.

My plan is not to return ALL the values held in the text file. As you say, that could be a very large list. Down the road, I intend to allow the devs to customize the number of values to check against, with 100 being the default.

**Comment by pachonk** [comment] 2017-09-08 19:30
RDS is like mysql, postgres, mssql, etc.

**Comment by bradseefeld** [comment] 2017-09-09 00:18
No, do not add a database dependency to this gem.

We just need to be able to config the path to the list. If you're that worried about removing passwords that are too long or too short from the list, filter those out when the list is loaded (the list should only be loaded once at boot anyway).

Passwords containing 'weak passwords' within them should be allowed. If my password is "this is a Str0ng password, but may look weak because its got some common dictionary words in it" then it should not be rejected! Passphrases are whats being suggested to users in a lot of apps and if their phrase includes one weak password string, it should not be rejected outright.

**Comment by pachonk** [comment] 2017-09-09 06:16
Without a database, I can't see scaling to extremely long password lists.
Could eventually have adapters to support Redis, ActiveRecord, local array, etc.

**Comment by HCLarsen** [comment] 2017-09-09 19:54
You mean a relational database? That would also require a lot of retooling. Not something I'm interested in doing.

**Comment by HCLarsen** [comment] 2017-09-09 19:58
@bradseefeld based on what you're saying there, I don't think you're understanding the point of this gem. The point is to prevent users from signing up using a password on the list of most common passwords. It does a direct match check between the entered password and the list. Nothing more.

**Comment by bradseefeld** [comment] 2017-09-09 22:02
@HCLarsen, I understand that... Im not sure where the miscommunication is. All I am requesting is to have the path to the list of passwords be configurable so that we can use our own list.

**Comment by HCLarsen** [comment] 2017-09-11 19:03
While I appreciate the feedback that both of you are providing, your suggestions do not fit within the use cases that this gem was designed to address. I'm closing this issue, as I don't see further discussions being helpful.

**Closed by HCLarsen** 2017-09-11 19:03 UTC
